//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicShop.DiscountServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiscountServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountDiscount", ReplyAction="http://tempuri.org/IService1/CountDiscountResponse")]
        int CountDiscount(int Price, int Discount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CountDiscount", ReplyAction="http://tempuri.org/IService1/CountDiscountResponse")]
        System.Threading.Tasks.Task<int> CountDiscountAsync(int Price, int Discount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MusicShop.DiscountServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MusicShop.DiscountServiceReference.IService1>, MusicShop.DiscountServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountDiscount(int Price, int Discount) {
            return base.Channel.CountDiscount(Price, Discount);
        }
        
        public System.Threading.Tasks.Task<int> CountDiscountAsync(int Price, int Discount) {
            return base.Channel.CountDiscountAsync(Price, Discount);
        }
    }
}
